name = "codey-daily"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "codey-daily"
database_id = "47878f0a-4d22-464b-83be-f77aad35bb0d"

[[kv_namespaces]]
binding = "KV"
id = "bdf849fb478d4d2dae185fc540682f1a"

[vars]
ENVIRONMENT = "production"
