-- Generated by generate-standard-seed.py
-- Claude Code 標準機能 60+項目のキュレーション

DELETE FROM features;

INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-clear',
  '/clear',
  'slash-command',
  '会話履歴をクリアして新しい状態から始める',
  '現在のセッションの会話履歴をクリア。メモリ（永続化された情報）は保持される。長時間のセッションで文脈をリセットしたい時に使う。',
  '[{"title": "履歴クリア", "code": "/clear"}]',
  '[]',
  1,
  'free',
  '[]',
  '/clear 会話履歴をクリアして新しい状態から始める 現在のセッションの会話履歴をクリア。メモリ（永続化された情報）は保持される。長時間のセッションで文脈をリセットしたい時に使う。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-help',
  '/help',
  'slash-command',
  '利用可能なコマンド一覧を表示',
  'Claude Code で使える組み込みコマンドの一覧を表示。困ったらまずこれ。',
  '[{"title": "ヘルプ表示", "code": "/help"}]',
  '[]',
  1,
  'free',
  '[]',
  '/help 利用可能なコマンド一覧を表示 claude code で使える組み込みコマンドの一覧を表示。困ったらまずこれ。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-memory',
  '/memory',
  'slash-command',
  'メモリーシステムを管理',
  'ユーザーの好み、プロジェクトの背景、フィードバックなどを永続的に蓄積するメモリーシステムを管理。将来の対話で自動的に参照される。',
  '[{"title": "メモリ確認", "code": "/memory"}]',
  '[]',
  2,
  'free',
  '["file-claude-md"]',
  '/memory メモリーシステムを管理 ユーザーの好み、プロジェクトの背景、フィードバックなどを永続的に蓄積するメモリーシステムを管理。将来の対話で自動的に参照される。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-agents',
  '/agents',
  'slash-command',
  'サブエージェントを管理',
  'サブエージェントの定義・起動・状態確認。複雑なタスクを並列実行する際に使う。Task tool と組み合わせる。',
  '[{"title": "エージェント一覧", "code": "/agents"}]',
  '[]',
  3,
  'free',
  '["tool-task", "agent-subagent"]',
  '/agents サブエージェントを管理 サブエージェントの定義・起動・状態確認。複雑なタスクを並列実行する際に使う。task tool と組み合わせる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-context',
  '/context',
  'slash-command',
  'コンテキストウィンドウ使用率を表示',
  '現在のセッションでのコンテキスト使用率を確認。長時間セッションでの圧縮タイミング判断に役立つ。',
  '[{"title": "使用量確認", "code": "/context"}]',
  '[]',
  1,
  'free',
  '["slash-compact"]',
  '/context コンテキストウィンドウ使用率を表示 現在のセッションでのコンテキスト使用率を確認。長時間セッションでの圧縮タイミング判断に役立つ。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-hooks',
  '/hooks',
  'slash-command',
  'フック設定を管理',
  'PreToolUse/PostToolUse/Stop等のイベントで自動実行するシェルスクリプトを設定。',
  '[{"title": "フック確認", "code": "/hooks"}]',
  '[]',
  4,
  'free',
  '["hook-pretooluse", "hook-posttooluse"]',
  '/hooks フック設定を管理 pretooluse/posttooluse/stop等のイベントで自動実行するシェルスクリプトを設定。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-init',
  '/init',
  'slash-command',
  'CLAUDE.md を初期化',
  '現在のリポジトリを分析して CLAUDE.md（プロジェクトガイダンスファイル）の雛形を生成。',
  '[{"title": "初期化", "code": "/init"}]',
  '[]',
  1,
  'free',
  '["file-claude-md"]',
  '/init claude.md を初期化 現在のリポジトリを分析して claude.md（プロジェクトガイダンスファイル）の雛形を生成。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-review',
  '/review',
  'slash-command',
  'プルリクエストをレビュー',
  '現在のブランチまたは指定PRをレビュー。コード品質、バグ可能性、改善提案を返す。',
  '[{"title": "PRレビュー", "code": "/review"}]',
  '[]',
  2,
  'free',
  '[]',
  '/review プルリクエストをレビュー 現在のブランチまたは指定prをレビュー。コード品質、バグ可能性、改善提案を返す。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-config',
  '/config',
  'slash-command',
  '設定を表示・変更',
  'テーマ、モデル、その他のユーザー設定を変更。settings.json の代替インタフェース。',
  '[{"title": "設定表示", "code": "/config"}]',
  '[]',
  1,
  'free',
  '["file-settings-json"]',
  '/config 設定を表示・変更 テーマ、モデル、その他のユーザー設定を変更。settings.json の代替インタフェース。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-model',
  '/model',
  'slash-command',
  '使用するモデルを切り替え',
  'Opus / Sonnet / Haiku など、現在のセッションで使用するモデルを切り替える。',
  '[{"title": "モデル切替", "code": "/model"}]',
  '[]',
  1,
  'free',
  '[]',
  '/model 使用するモデルを切り替え opus / sonnet / haiku など、現在のセッションで使用するモデルを切り替える。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-status',
  '/status',
  'slash-command',
  'セッション状態を表示',
  '現在のセッションの統計情報（モデル、ディレクトリ、git状態など）を表示。',
  '[{"title": "状態確認", "code": "/status"}]',
  '[]',
  1,
  'free',
  '[]',
  '/status セッション状態を表示 現在のセッションの統計情報（モデル、ディレクトリ、git状態など）を表示。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-cost',
  '/cost',
  'slash-command',
  'API利用コストを表示',
  '現在のセッションでのAPIトークン使用量とコストを確認。',
  '[{"title": "コスト確認", "code": "/cost"}]',
  '[]',
  1,
  'free',
  '[]',
  '/cost api利用コストを表示 現在のセッションでのapiトークン使用量とコストを確認。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-compact',
  '/compact',
  'slash-command',
  'コンテキストを強制圧縮',
  'コンテキストが膨らんだとき、過去の会話を要約して圧縮。重要な情報は保持。',
  '[{"title": "圧縮実行", "code": "/compact"}]',
  '[]',
  2,
  'free',
  '["slash-context", "hook-precompact"]',
  '/compact コンテキストを強制圧縮 コンテキストが膨らんだとき、過去の会話を要約して圧縮。重要な情報は保持。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-resume',
  '/resume',
  'slash-command',
  '前回のセッションを再開',
  '終了したセッションを再開して続きから作業を再開。',
  '[{"title": "再開", "code": "/resume"}]',
  '[]',
  1,
  'free',
  '["cli-resume"]',
  '/resume 前回のセッションを再開 終了したセッションを再開して続きから作業を再開。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'slash-security-review',
  '/security-review',
  'slash-command',
  'セキュリティレビューを実施',
  '現在のブランチの変更内容に対してセキュリティ観点のレビューを実行。',
  '[{"title": "セキュリティ確認", "code": "/security-review"}]',
  '[]',
  2,
  'free',
  '["slash-review"]',
  '/security-review セキュリティレビューを実施 現在のブランチの変更内容に対してセキュリティ観点のレビューを実行。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-bash',
  'Bash',
  'tool',
  'シェルコマンドを実行',
  'シェル環境でコマンドを実行。npm install、git操作、ビルドコマンドなどに使う。最大10分のタイムアウト指定可能。',
  '[{"title": "git status実行", "code": "Bash: git status"}]',
  '[]',
  1,
  'free',
  '[]',
  'bash シェルコマンドを実行 シェル環境でコマンドを実行。npm install、git操作、ビルドコマンドなどに使う。最大10分のタイムアウト指定可能。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-read',
  'Read',
  'tool',
  'ファイルを読み取り',
  'ファイルの内容を読み取る。テキスト、PDF、画像、Jupyter notebookに対応。行番号付き、オフセット指定可能。',
  '[{"title": "ファイル読込", "code": "Read: /path/to/file.ts"}]',
  '[]',
  1,
  'free',
  '["tool-write", "tool-edit"]',
  'read ファイルを読み取り ファイルの内容を読み取る。テキスト、pdf、画像、jupyter notebookに対応。行番号付き、オフセット指定可能。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-write',
  'Write',
  'tool',
  '新規ファイルを作成',
  'ローカルファイルシステムにファイルを作成・上書き。既存ファイルは事前に Read 必須。',
  '[{"title": "新規作成", "code": "Write: 新ファイルを書き出す"}]',
  '[]',
  1,
  'free',
  '["tool-read", "tool-edit"]',
  'write 新規ファイルを作成 ローカルファイルシステムにファイルを作成・上書き。既存ファイルは事前に read 必須。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-edit',
  'Edit',
  'tool',
  '既存ファイルを部分編集',
  'old_string と new_string を指定して文字列置換。差分のみ送信できるので Write より効率的。',
  '[{"title": "文字列置換", "code": "Edit: old_string → new_string"}]',
  '[]',
  2,
  'free',
  '["tool-multiedit", "tool-write"]',
  'edit 既存ファイルを部分編集 old_string と new_string を指定して文字列置換。差分のみ送信できるので write より効率的。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-multiedit',
  'MultiEdit',
  'tool',
  '1ファイルに複数編集を一括適用',
  '複数の Edit 操作を同時にトランザクションで適用。1つでも失敗すると全てロールバック。',
  '[{"title": "複数編集", "code": "MultiEdit: 編集A,編集B,編集C"}]',
  '[]',
  3,
  'free',
  '["tool-edit"]',
  'multiedit 1ファイルに複数編集を一括適用 複数の edit 操作を同時にトランザクションで適用。1つでも失敗すると全てロールバック。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-glob',
  'Glob',
  'tool',
  'パターンでファイル検索',
  'ワイルドカードパターン（src/**/*.ts等）でファイルを高速検索。',
  '[{"title": "TS検索", "code": "Glob: src/**/*.ts"}]',
  '[]',
  1,
  'free',
  '["tool-grep"]',
  'glob パターンでファイル検索 ワイルドカードパターン（src/**/*.ts等）でファイルを高速検索。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-grep',
  'Grep',
  'tool',
  'ファイル内容を全文検索',
  'ripgrepベースの高速検索。正規表現対応、コンテキスト行表示、ファイル種別フィルタなど多機能。',
  '[{"title": "関数定義検索", "code": "Grep: \"function login\""}]',
  '[]',
  2,
  'free',
  '["tool-glob"]',
  'grep ファイル内容を全文検索 ripgrepベースの高速検索。正規表現対応、コンテキスト行表示、ファイル種別フィルタなど多機能。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-task',
  'Task (Agent)',
  'tool',
  'サブエージェントを起動',
  '別のエージェントを起動して並列タスク実行。Explore/Plan/general-purpose 等の組み込みエージェントを使える。',
  '[{"title": "サブエージェント起動", "code": "Task: subagent_type=Explore"}]',
  '[]',
  3,
  'free',
  '["agent-subagent", "agent-explore", "agent-plan"]',
  'task (agent) サブエージェントを起動 別のエージェントを起動して並列タスク実行。explore/plan/general-purpose 等の組み込みエージェントを使える。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-websearch',
  'WebSearch',
  'tool',
  'Webを検索',
  '最新情報を検索。日付・ドメインフィルタ対応。米国限定。',
  '[{"title": "最新情報検索", "code": "WebSearch: \"Claude Code 2026\""}]',
  '[]',
  1,
  'free',
  '["tool-webfetch"]',
  'websearch webを検索 最新情報を検索。日付・ドメインフィルタ対応。米国限定。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-webfetch',
  'WebFetch',
  'tool',
  'URLを取得して要約',
  '指定URLからHTML取得→マークダウン変換→AIが要約。15分キャッシュあり。',
  '[{"title": "ドキュメント取得", "code": "WebFetch: docs.anthropic.com/..."}]',
  '[]',
  1,
  'free',
  '["tool-websearch"]',
  'webfetch urlを取得して要約 指定urlからhtml取得→マークダウン変換→aiが要約。15分キャッシュあり。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-notebookedit',
  'NotebookEdit',
  'tool',
  'Jupyter Notebookセルを編集',
  '.ipynb ファイルの特定セルを編集・追加・削除。データサイエンス作業向け。',
  '[{"title": "セル編集", "code": "NotebookEdit: cell_id=...,new_source=..."}]',
  '[]',
  2,
  'free',
  '["tool-edit"]',
  'notebookedit jupyter notebookセルを編集 .ipynb ファイルの特定セルを編集・追加・削除。データサイエンス作業向け。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-todowrite',
  'TodoWrite',
  'tool',
  'タスクリストで進捗管理',
  '現在のセッション内のタスク追跡。pending/in_progress/completed の3状態。複雑な作業の整理に。',
  '[{"title": "タスク追加", "code": "TodoWrite: 認証実装、テスト追加"}]',
  '[]',
  1,
  'free',
  '[]',
  'todowrite タスクリストで進捗管理 現在のセッション内のタスク追跡。pending/in_progress/completed の3状態。複雑な作業の整理に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'tool-slashcommand',
  'SlashCommand',
  'tool',
  '別のスラッシュコマンドを実行',
  'Claude が他のスラッシュコマンドを呼び出す内部ツール。コマンド連携の基盤。',
  '[{"title": "コマンド呼出", "code": "SlashCommand: /init"}]',
  '[]',
  3,
  'free',
  '[]',
  'slashcommand 別のスラッシュコマンドを実行 claude が他のスラッシュコマンドを呼び出す内部ツール。コマンド連携の基盤。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-pretooluse',
  'PreToolUse Hook',
  'hook',
  'ツール実行前のフック',
  'ツール実行直前に走るフック。matcher で対象ツール指定、危険コマンドのブロックや事前検証に使える。',
  '[{"title": "rm -rf ブロック", "code": "matcher: \"Bash\", action: block on rm -rf"}]',
  '[]',
  4,
  'free',
  '["hook-posttooluse", "slash-hooks"]',
  'pretooluse hook ツール実行前のフック ツール実行直前に走るフック。matcher で対象ツール指定、危険コマンドのブロックや事前検証に使える。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-posttooluse',
  'PostToolUse Hook',
  'hook',
  'ツール実行後のフック',
  'ツール実行直後に走るフック。ログ記録、自動フォーマット、テスト実行などに使う。',
  '[{"title": "編集後にprettier", "code": "matcher: Edit/Write -> npx prettier"}]',
  '[]',
  4,
  'free',
  '["hook-pretooluse"]',
  'posttooluse hook ツール実行後のフック ツール実行直後に走るフック。ログ記録、自動フォーマット、テスト実行などに使う。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-stop',
  'Stop Hook',
  'hook',
  'Claude応答完了時のフック',
  'Claudeの応答が終了したときに走るフック。完了通知やセッションログ出力に。',
  '[{"title": "通知音", "code": "Stop: afplay /sound.wav"}]',
  '[]',
  3,
  'free',
  '["hook-subagentstop"]',
  'stop hook claude応答完了時のフック claudeの応答が終了したときに走るフック。完了通知やセッションログ出力に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-subagentstop',
  'SubagentStop Hook',
  'hook',
  'サブエージェント完了時のフック',
  'サブエージェント（Task tool）が完了したときに走るフック。',
  '[{"title": "サブエージェント完了通知", "code": "SubagentStop: log to file"}]',
  '[]',
  4,
  'free',
  '["hook-stop"]',
  'subagentstop hook サブエージェント完了時のフック サブエージェント（task tool）が完了したときに走るフック。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-sessionstart',
  'SessionStart Hook',
  'hook',
  'セッション開始時のフック',
  'Claude Code セッション開始時に走るフック。git pull や初期メッセージ表示に。',
  '[{"title": "git pull", "code": "SessionStart: git pull"}]',
  '[]',
  3,
  'free',
  '["hook-sessionend"]',
  'sessionstart hook セッション開始時のフック claude code セッション開始時に走るフック。git pull や初期メッセージ表示に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-sessionend',
  'SessionEnd Hook',
  'hook',
  'セッション終了時のフック',
  'セッション終了時に走るフック。コミット忘れ警告、サマリー出力など。',
  '[{"title": "未コミット警告", "code": "SessionEnd: git status check"}]',
  '[]',
  3,
  'free',
  '["hook-sessionstart"]',
  'sessionend hook セッション終了時のフック セッション終了時に走るフック。コミット忘れ警告、サマリー出力など。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-userpromptsubmit',
  'UserPromptSubmit Hook',
  'hook',
  'ユーザー入力送信時のフック',
  'ユーザーがプロンプトを送信した直後に走る。入力内容を加工・追記したり、追加コンテキスト注入に使える。',
  '[{"title": "翻訳指示自動追加", "code": "UserPromptSubmit: 日本語入力に英訳ヒント追加"}]',
  '[]',
  4,
  'free',
  '[]',
  'userpromptsubmit hook ユーザー入力送信時のフック ユーザーがプロンプトを送信した直後に走る。入力内容を加工・追記したり、追加コンテキスト注入に使える。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-precompact',
  'PreCompact Hook',
  'hook',
  'コンテキスト圧縮直前のフック',
  'コンテキスト圧縮が走る直前に呼ばれる。圧縮前に重要な情報を保存したい時に。',
  '[{"title": "圧縮前のスナップショット", "code": "PreCompact: dump to file"}]',
  '[]',
  4,
  'free',
  '["slash-compact"]',
  'precompact hook コンテキスト圧縮直前のフック コンテキスト圧縮が走る直前に呼ばれる。圧縮前に重要な情報を保存したい時に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'hook-notification',
  'Notification Hook',
  'hook',
  '通知イベントのフック',
  'Claudeが通知を出すタイミング（権限要求等）で走るフック。デスクトップ通知連携などに。',
  '[{"title": "macOS通知", "code": "Notification: osascript display notification"}]',
  '[]',
  3,
  'free',
  '[]',
  'notification hook 通知イベントのフック claudeが通知を出すタイミング（権限要求等）で走るフック。デスクトップ通知連携などに。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mode-plan',
  'Plan Mode',
  'mode',
  '読み取り専用の計画モード',
  'Shift+Tabで切替。コードを書かずに「これからやること」を提案するだけ。実装前のレビューに最適。',
  '[{"title": "切替", "code": "Shift + Tab"}]',
  '[]',
  2,
  'free',
  '["agent-plan"]',
  'plan mode 読み取り専用の計画モード shift+tabで切替。コードを書かずに「これからやること」を提案するだけ。実装前のレビューに最適。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mode-permission',
  'Permission Modes',
  'mode',
  'ツール実行時の確認制御',
  'default(都度確認)、acceptEdits(編集自動)、bypassPermissions(全自動)、plan(読取のみ)の4モード。',
  '[{"title": "自動編集モード", "code": "permissionMode: acceptEdits"}]',
  '[]',
  2,
  'free',
  '["mode-plan"]',
  'permission modes ツール実行時の確認制御 default(都度確認)、acceptedits(編集自動)、bypasspermissions(全自動)、plan(読取のみ)の4モード。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mode-output-style',
  'Output Styles',
  'mode',
  '応答スタイルのカスタマイズ',
  'Claudeの応答口調・形式を調整。簡潔モード、教育モードなどプリセットあり。',
  '[{"title": "切替", "code": "/output-style"}]',
  '[]',
  2,
  'free',
  '[]',
  'output styles 応答スタイルのカスタマイズ claudeの応答口調・形式を調整。簡潔モード、教育モードなどプリセットあり。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mode-headless',
  'Headless Mode (--print)',
  'mode',
  '対話なしで一発実行',
  '--print フラグで対話UIなしに1回だけプロンプトを実行して結果を返す。CIやスクリプト統合に。',
  '[{"title": "ヘッドレス実行", "code": "claude --print \"PRレビューして\""}]',
  '[]',
  2,
  'free',
  '["cli-print"]',
  'headless mode (--print) 対話なしで一発実行 --print フラグで対話uiなしに1回だけプロンプトを実行して結果を返す。ciやスクリプト統合に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-claude-md',
  'CLAUDE.md',
  'file',
  'プロジェクトガイダンスファイル',
  'リポジトリ直下に置くと Claude が自動的に読み込むプロジェクトガイダンス。コーディング規約、ディレクトリ構造、注意事項などを書く。',
  '[{"title": "雛形生成", "code": "/init"}]',
  '[]',
  1,
  'free',
  '["slash-init", "file-agents-md"]',
  'claude.md プロジェクトガイダンスファイル リポジトリ直下に置くと claude が自動的に読み込むプロジェクトガイダンス。コーディング規約、ディレクトリ構造、注意事項などを書く。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-agents-md',
  'AGENTS.md',
  'file',
  'エージェント定義ファイル',
  'サブエージェントの挙動を定義。CLAUDE.md と並列で機能する場合あり。',
  '[{"title": "ファイル配置", "code": "プロジェクトルートに配置"}]',
  '[]',
  2,
  'free',
  '["file-claude-md"]',
  'agents.md エージェント定義ファイル サブエージェントの挙動を定義。claude.md と並列で機能する場合あり。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-onboarding-md',
  'ONBOARDING.md',
  'file',
  '新規参加者向けガイド',
  'プロジェクトに初めて触れる人のためのオンボーディング情報。Claude が読み込んでアシストに使う。',
  '[{"title": "ファイル配置", "code": "プロジェクトルートに配置"}]',
  '[]',
  1,
  'free',
  '["file-claude-md"]',
  'onboarding.md 新規参加者向けガイド プロジェクトに初めて触れる人のためのオンボーディング情報。claude が読み込んでアシストに使う。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-settings-json',
  'settings.json',
  'file',
  'ユーザー全体の設定ファイル',
  '~/.claude/settings.json でグローバル設定。テーマ、フック、許可リスト、環境変数など。',
  '[{"title": "場所", "code": "~/.claude/settings.json"}]',
  '[]',
  2,
  'free',
  '["file-settings-local-json", "slash-config"]',
  'settings.json ユーザー全体の設定ファイル ~/.claude/settings.json でグローバル設定。テーマ、フック、許可リスト、環境変数など。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-settings-local-json',
  'settings.local.json',
  'file',
  'プロジェクト固有設定',
  '.claude/settings.local.json でプロジェクト単位設定。git管理外、個人の許可設定などに。',
  '[{"title": "場所", "code": ".claude/settings.local.json"}]',
  '[]',
  2,
  'free',
  '["file-settings-json"]',
  'settings.local.json プロジェクト固有設定 .claude/settings.local.json でプロジェクト単位設定。git管理外、個人の許可設定などに。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-mcp-json',
  '.mcp.json',
  'file',
  'MCPサーバー設定ファイル',
  'プロジェクトに紐づく MCP サーバーを定義。stdio/SSE/HTTP の各種MCPサーバーを登録できる。',
  '[{"title": "場所", "code": ".mcp.json"}]',
  '[]',
  3,
  'free',
  '["mcp-overview"]',
  '.mcp.json mcpサーバー設定ファイル プロジェクトに紐づく mcp サーバーを定義。stdio/sse/http の各種mcpサーバーを登録できる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-memory',
  'Memory System',
  'file',
  '永続メモリシステム',
  '~/.claude/projects/<hash>/memory/ にユーザー嗜好・プロジェクト情報を蓄積。MEMORY.md がインデックス。',
  '[{"title": "場所", "code": "~/.claude/projects/.../memory/"}]',
  '[]',
  3,
  'free',
  '["slash-memory"]',
  'memory system 永続メモリシステム ~/.claude/projects/<hash>/memory/ にユーザー嗜好・プロジェクト情報を蓄積。memory.md がインデックス。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'file-mention',
  '@-mentions',
  'file',
  'ファイルを@で参照',
  'プロンプト内で @path/to/file と書くと、そのファイルが自動的にコンテキストに追加される。',
  '[{"title": "ファイル参照", "code": "@src/index.ts のバグを直して"}]',
  '[]',
  1,
  'free',
  '[]',
  '@-mentions ファイルを@で参照 プロンプト内で @path/to/file と書くと、そのファイルが自動的にコンテキストに追加される。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'cli-continue',
  '--continue (-c)',
  'cli',
  '前回のセッションを継続',
  'claude --continue で直前のセッションをそのまま再開。コンテキストを失わずに続けられる。',
  '[{"title": "継続実行", "code": "claude -c"}]',
  '[]',
  1,
  'free',
  '["cli-resume", "slash-resume"]',
  '--continue (-c) 前回のセッションを継続 claude --continue で直前のセッションをそのまま再開。コンテキストを失わずに続けられる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'cli-resume',
  '--resume (-r)',
  'cli',
  '特定セッションを再開',
  'claude --resume <session-id> で過去の任意セッションを再開。',
  '[{"title": "セッション選択再開", "code": "claude -r"}]',
  '[]',
  2,
  'free',
  '["cli-continue"]',
  '--resume (-r) 特定セッションを再開 claude --resume <session-id> で過去の任意セッションを再開。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'cli-print',
  '--print (-p)',
  'cli',
  'ヘッドレスモードで一発実行',
  '対話UIを起動せずプロンプトを実行して結果を出力。スクリプト連携に。',
  '[{"title": "ヘッドレス", "code": "claude -p \"PR要約して\""}]',
  '[]',
  2,
  'free',
  '["mode-headless"]',
  '--print (-p) ヘッドレスモードで一発実行 対話uiを起動せずプロンプトを実行して結果を出力。スクリプト連携に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'cli-model',
  '--model',
  'cli',
  '使用モデルを起動時に指定',
  'claude --model claude-opus-4-7 のように、起動時に使用モデルを固定。',
  '[{"title": "Opus指定起動", "code": "claude --model claude-opus-4-7"}]',
  '[]',
  1,
  'free',
  '["slash-model"]',
  '--model 使用モデルを起動時に指定 claude --model claude-opus-4-7 のように、起動時に使用モデルを固定。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'cli-add-dir',
  '--add-dir',
  'cli',
  '追加の作業ディレクトリを指定',
  'Claude のアクセスを通常のcwd以外にも広げる。複数リポジトリを横断する作業に。',
  '[{"title": "別リポ追加", "code": "claude --add-dir ../other-repo"}]',
  '[]',
  2,
  'free',
  '[]',
  '--add-dir 追加の作業ディレクトリを指定 claude のアクセスを通常のcwd以外にも広げる。複数リポジトリを横断する作業に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-subagent',
  'Subagent System',
  'agent',
  'サブエージェントの仕組み',
  'メインのClaudeとは別の文脈で動く専門エージェント。Task tool 経由で起動。複雑タスクの並列処理や文脈分離に。',
  '[{"title": "起動例", "code": "Task: subagent_type=Explore"}]',
  '[]',
  3,
  'free',
  '["tool-task", "slash-agents"]',
  'subagent system サブエージェントの仕組み メインのclaudeとは別の文脈で動く専門エージェント。task tool 経由で起動。複雑タスクの並列処理や文脈分離に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-explore',
  'Explore Agent',
  'agent',
  '高速読み取り検索エージェント',
  'コードを探すための読み取り専用検索エージェント。パターン・キーワード・シンボル検索に最適。並列実行で本体の文脈を消費しない。',
  '[{"title": "コンポーネント検索", "code": "Task: subagent_type=Explore で\"src/components/**/*.tsx\"検索"}]',
  '[]',
  2,
  'free',
  '["agent-subagent", "tool-glob"]',
  'explore agent 高速読み取り検索エージェント コードを探すための読み取り専用検索エージェント。パターン・キーワード・シンボル検索に最適。並列実行で本体の文脈を消費しない。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-plan',
  'Plan Agent',
  'agent',
  '実装計画を設計するエージェント',
  'タスクの実装戦略を設計。ステップバイステップ計画、重要ファイル特定、アーキテクチャトレードオフ考慮。',
  '[{"title": "新機能計画", "code": "Task: subagent_type=Plan で認証機能の実装計画"}]',
  '[]',
  2,
  'free',
  '["agent-subagent", "mode-plan"]',
  'plan agent 実装計画を設計するエージェント タスクの実装戦略を設計。ステップバイステップ計画、重要ファイル特定、アーキテクチャトレードオフ考慮。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-general-purpose',
  'general-purpose Agent',
  'agent',
  '汎用エージェント',
  '特化していない汎用エージェント。複雑な調査やマルチステップタスクに使える。',
  '[{"title": "汎用調査", "code": "Task: subagent_type=general-purpose"}]',
  '[]',
  2,
  'free',
  '["agent-subagent"]',
  'general-purpose agent 汎用エージェント 特化していない汎用エージェント。複雑な調査やマルチステップタスクに使える。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-custom',
  'Custom Subagents',
  'agent',
  '独自サブエージェントの作成',
  '.claude/agents/<name>.md にエージェント定義を置くと、自分専用のサブエージェントが作れる。',
  '[{"title": "ファイル配置", "code": ".claude/agents/my-agent.md"}]',
  '[]',
  4,
  'free',
  '["agent-subagent"]',
  'custom subagents 独自サブエージェントの作成 .claude/agents/<name>.md にエージェント定義を置くと、自分専用のサブエージェントが作れる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'agent-isolation',
  'Worktree Isolation',
  'agent',
  'git worktreeでエージェント隔離',
  'サブエージェントを別のgit worktreeで動かしてmainと隔離。並列開発の事故防止に。',
  '[{"title": "隔離起動", "code": "Task: isolation=worktree"}]',
  '[]',
  4,
  'free',
  '["agent-subagent"]',
  'worktree isolation git worktreeでエージェント隔離 サブエージェントを別のgit worktreeで動かしてmainと隔離。並列開発の事故防止に。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'skill-overview',
  'Skills System',
  'skill',
  '再利用可能なスキルシステム',
  '.claude/skills/<name>/SKILL.md でスキル定義。description のキーワードでトリガーされ、Claudeが自動的に呼び出す。',
  '[{"title": "ファイル配置", "code": ".claude/skills/my-skill/SKILL.md"}]',
  '[]',
  3,
  'free',
  '["skill-structure"]',
  'skills system 再利用可能なスキルシステム .claude/skills/<name>/skill.md でスキル定義。description のキーワードでトリガーされ、claudeが自動的に呼び出す。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'skill-structure',
  'SKILL.md Structure',
  'skill',
  'スキル定義ファイルの構造',
  'frontmatter に description（トリガー文）、name、tools などを書く。本文は手順・ルール・テンプレート。',
  '[{"title": "雛形", "code": "---\\nname: my-skill\\ndescription: ...\\n---"}]',
  '[]',
  4,
  'free',
  '["skill-overview"]',
  'skill.md structure スキル定義ファイルの構造 frontmatter に description（トリガー文）、name、tools などを書く。本文は手順・ルール・テンプレート。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'skill-marketplace',
  'Plugin Marketplace',
  'skill',
  '公式プラグインマーケット',
  'Anthropic公式や有志によるプラグイン（スキル/エージェントのバンドル）を配布・取得できるマーケット。',
  '[{"title": "閲覧", "code": "/marketplace"}]',
  '[]',
  2,
  'free',
  '["skill-overview"]',
  'plugin marketplace 公式プラグインマーケット anthropic公式や有志によるプラグイン（スキル/エージェントのバンドル）を配布・取得できるマーケット。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'skill-trigger',
  'Skill Triggers',
  'skill',
  'スキルの自動起動トリガー',
  'SKILL.md の description に書いたキーワードが入力にマッチすると Claude が自動でスキルを呼び出す仕組み。',
  '[{"title": "description例", "code": "description: PRレビューしたい時に使う"}]',
  '[]',
  3,
  'free',
  '["skill-overview"]',
  'skill triggers スキルの自動起動トリガー skill.md の description に書いたキーワードが入力にマッチすると claude が自動でスキルを呼び出す仕組み。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mcp-overview',
  'MCP Overview',
  'mcp',
  'Model Context Protocol',
  '外部ツール・APIをClaudeに統合するためのオープンプロトコル。GitHub、Slack、DBなどへの橋渡し。',
  '[{"title": "設定ファイル", "code": ".mcp.json"}]',
  '[]',
  3,
  'free',
  '["file-mcp-json", "mcp-stdio", "mcp-sse", "mcp-http"]',
  'mcp overview model context protocol 外部ツール・apiをclaudeに統合するためのオープンプロトコル。github、slack、dbなどへの橋渡し。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mcp-stdio',
  'MCP stdio Server',
  'mcp',
  '標準入出力ベースのMCPサーバー',
  'プロセス起動して stdin/stdout でやりとりするMCPサーバー。最も一般的。Pythonやnpx で簡単に動かせる。',
  '[{"title": "設定例", "code": "type: stdio, command: npx, args: [...]"}]',
  '[]',
  4,
  'free',
  '["mcp-overview"]',
  'mcp stdio server 標準入出力ベースのmcpサーバー プロセス起動して stdin/stdout でやりとりするmcpサーバー。最も一般的。pythonやnpx で簡単に動かせる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mcp-sse',
  'MCP SSE Server',
  'mcp',
  'Server-Sent Events型のMCPサーバー',
  'HTTP経由でストリーミング通信するMCPサーバー。クラウドホスト型サービスに向く。',
  '[{"title": "設定例", "code": "type: sse, url: https://..."}]',
  '[]',
  4,
  'free',
  '["mcp-overview"]',
  'mcp sse server server-sent events型のmcpサーバー http経由でストリーミング通信するmcpサーバー。クラウドホスト型サービスに向く。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'mcp-http',
  'MCP HTTP Server',
  'mcp',
  'REST/HTTP型のMCPサーバー',
  '標準的なHTTPでやり取りするMCPサーバー。シンプルなリクエスト/レスポンスモデル。',
  '[{"title": "設定例", "code": "type: http, url: https://..."}]',
  '[]',
  4,
  'free',
  '["mcp-overview"]',
  'mcp http server rest/http型のmcpサーバー 標準的なhttpでやり取りするmcpサーバー。シンプルなリクエスト/レスポンスモデル。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'misc-statusline',
  'Status Line',
  'setting',
  'プロンプト下部のカスタム表示',
  'git ブランチ、モデル名、コンテキスト残量など、自分の好みに合わせて統合バーを表示できる。',
  '[{"title": "skill経由設定", "code": "/statusline-setup"}]',
  '[]',
  3,
  'free',
  '[]',
  'status line プロンプト下部のカスタム表示 git ブランチ、モデル名、コンテキスト残量など、自分の好みに合わせて統合バーを表示できる。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'misc-keybindings',
  'Keybindings',
  'setting',
  'キーボードショートカット',
  '~/.claude/keybindings.json でキー割当をカスタマイズ。chord（複数キー）対応。',
  '[{"title": "ファイル", "code": "~/.claude/keybindings.json"}]',
  '[]',
  3,
  'free',
  '[]',
  'keybindings キーボードショートカット ~/.claude/keybindings.json でキー割当をカスタマイズ。chord（複数キー）対応。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'misc-ide-vscode',
  'VS Code Extension',
  'setting',
  'VS Code拡張機能',
  'VS CodeにClaude Codeを統合。エディタ内でClaudeと対話、現在のファイル/選択範囲を即文脈化。',
  '[{"title": "インストール", "code": "VS Code Marketplace で検索"}]',
  '[]',
  1,
  'free',
  '[]',
  'vs code extension vs code拡張機能 vs codeにclaude codeを統合。エディタ内でclaudeと対話、現在のファイル/選択範囲を即文脈化。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'misc-ide-jetbrains',
  'JetBrains Plugin',
  'setting',
  'JetBrains IDE プラグイン',
  'IntelliJ / WebStorm / PyCharm などへClaude Codeを統合。VS Code版と同等。',
  '[{"title": "インストール", "code": "JetBrains Marketplace"}]',
  '[]',
  1,
  'free',
  '[]',
  'jetbrains plugin jetbrains ide プラグイン intellij / webstorm / pycharm などへclaude codeを統合。vs code版と同等。'
);
INSERT INTO features (id, name, category, summary_ja, description_ja, examples, links, difficulty, tier, related, search_text)
VALUES (
  'misc-fast-mode',
  'Fast Mode',
  'setting',
  '高速応答モード',
  '/fast コマンドで Opus 4.6 ベースの高速応答に切替。Opus 4.6 でのみ利用可能。',
  '[{"title": "切替", "code": "/fast"}]',
  '[]',
  1,
  'free',
  '["slash-model"]',
  'fast mode 高速応答モード /fast コマンドで opus 4.6 ベースの高速応答に切替。opus 4.6 でのみ利用可能。'
);